import type { HorrorDomainKit } from "../domainKit";
import {
  createMeshGeneratingObjectKit,
  createMeshGeneratingObjectKitConfig,
  createMeshObjectDescriptor,
  type MeshGeneratingObjectKitConfig,
  type MeshObjectPartSpec,
  type MeshObjectProfile,
} from "../mesh-object-kit";

const slab = (
  id: string,
  label: string,
  materialFamily: string,
  thickness: number,
  topFace: Extract<MeshObjectPartSpec, { shape: "convex-slab" }>["topFace"],
  ...tags: string[]
): MeshObjectPartSpec => ({
  id,
  label,
  shape: "convex-slab",
  topFace,
  thickness,
  materialFamily,
  tags,
});

export const collapsedCeilingObjectProfile = {
  kitId: "collapsed-ceiling-object-kit",
  title: "Collapsed Ceiling Object Kit",
  domain: "collapsed-ceiling-object",
  services: [
    "broken-aperture-mesh",
    "wall-rooted-ceiling-profile",
    "fracture-relief-profile",
  ],
  propKind: "collapsed-ceiling",
  materialFamilies: [
    "damp-concrete",
    "broken-brick",
    "rusted-metal",
    "fracture-shadow",
  ],
  shaderProfile: "concrete-slab",
  palette: [0x343833, 0x50372d, 0x33271f],
  maxVisible: 4,
  purpose:
    "Reusable ruined-ceiling object whose thick fractured banks stay rooted in the surrounding shelter and walls while leaving one irregular daylight aperture.",
  targetTraits: [
    "one readable collapsed aperture",
    "thick wall-rooted concrete banks",
    "jagged inward fracture line",
    "broken brick material changes",
    "fine aperture-radial fracture relief",
    "small chipped edge fragments",
    "short embedded steel remnants",
    "clear traversable space below",
  ],
  placementTags: ["ceiling-mounted", "ruin-boundary", "non-blocking"],
  parts: [
    slab(
      "left-near-bank",
      "left wall near collapsed bank",
      "damp-concrete",
      0.34,
      [
        { x: -2.5, y: 0.2, z: -4.85 },
        { x: -2.42, y: -0.04, z: -1.55 },
        { x: 0.12, y: -0.38, z: -1.32 },
        { x: 0.05, y: 0.18, z: -4.8 },
      ],
      "left-bank",
      "wall-rooted",
      "primary-slab",
    ),
    slab(
      "left-far-bank",
      "left wall far collapsed bank",
      "broken-brick",
      0.38,
      [
        { x: -0.12, y: 0.16, z: -4.8 },
        { x: 0, y: -0.36, z: -1.28 },
        { x: 2.38, y: -0.08, z: -1.48 },
        { x: 2.5, y: 0.18, z: -4.75 },
      ],
      "left-bank",
      "wall-rooted",
      "brick-break",
    ),
    slab(
      "right-near-bank",
      "right wall near collapsed bank",
      "broken-brick",
      0.36,
      [
        { x: -2.45, y: -0.02, z: 1.48 },
        { x: -2.52, y: 0.18, z: 4.78 },
        { x: 0.08, y: 0.15, z: 4.85 },
        { x: 0.15, y: -0.4, z: 1.3 },
      ],
      "right-bank",
      "wall-rooted",
      "brick-break",
    ),
    slab(
      "right-far-bank",
      "right wall far collapsed bank",
      "damp-concrete",
      0.34,
      [
        { x: -0.12, y: -0.37, z: 1.25 },
        { x: -0.02, y: 0.17, z: 4.82 },
        { x: 2.45, y: 0.16, z: 4.75 },
        { x: 2.35, y: -0.06, z: 1.5 },
      ],
      "right-bank",
      "wall-rooted",
      "primary-slab",
    ),
    slab(
      "near-lip",
      "near shelter fractured lip",
      "damp-concrete",
      0.42,
      [
        { x: -2.5, y: 0.2, z: -1.6 },
        { x: -2.45, y: 0.18, z: 1.52 },
        { x: -1.05, y: -0.42, z: 1.15 },
        { x: -1.18, y: -0.34, z: -1.04 },
      ],
      "near-lip",
      "shelter-rooted",
      "low-fracture",
    ),
    slab(
      "far-lip",
      "far shelter fractured lip",
      "broken-brick",
      0.4,
      [
        { x: 1.28, y: -0.36, z: -1.03 },
        { x: 1.2, y: -0.4, z: 1.2 },
        { x: 2.38, y: 0.17, z: 1.52 },
        { x: 2.45, y: 0.2, z: -1.45 },
      ],
      "far-lip",
      "shelter-rooted",
      "brick-break",
    ),
    slab(
      "left-inner-fang",
      "left inward hanging fracture",
      "damp-concrete",
      0.3,
      [
        { x: 0.02, y: -0.36, z: -1.34 },
        { x: 0.36, y: -0.62, z: -0.58 },
        { x: 0.88, y: -0.34, z: -1.16 },
      ],
      "left-bank",
      "inner-fang",
      "edge-fragment",
    ),
    slab(
      "right-inner-fang",
      "right inward hanging fracture",
      "broken-brick",
      0.28,
      [
        { x: -0.7, y: -0.34, z: 1.28 },
        { x: -0.25, y: -0.6, z: 0.58 },
        { x: 0.12, y: -0.38, z: 1.3 },
      ],
      "right-bank",
      "inner-fang",
      "edge-fragment",
    ),
    slab(
      "left-steel-remnant",
      "left embedded snapped steel remnant",
      "rusted-metal",
      0.16,
      [
        { x: -2.22, y: -0.38, z: -4.36 },
        { x: -2.16, y: -0.4, z: -4.04 },
        { x: 0.34, y: -0.58, z: -1.42 },
        { x: 0.48, y: -0.56, z: -1.58 },
      ],
      "left-bank",
      "embedded-steel",
      "snapped-span",
    ),
    slab(
      "right-steel-remnant",
      "right embedded snapped steel remnant",
      "rusted-metal",
      0.15,
      [
        { x: 0.42, y: -0.56, z: 1.52 },
        { x: 0.3, y: -0.58, z: 1.36 },
        { x: 2.22, y: -0.4, z: 4.08 },
        { x: 2.3, y: -0.38, z: 4.38 },
      ],
      "right-bank",
      "embedded-steel",
      "snapped-span",
    ),
    slab(
      "near-left-edge-chip",
      "near-left chipped aperture edge",
      "damp-concrete",
      0.16,
      [
        { x: -1.15, y: -0.48, z: -0.92 },
        { x: -0.72, y: -0.7, z: -0.35 },
        { x: -0.42, y: -0.46, z: -0.88 },
      ],
      "near-lip",
      "edge-fragment",
      "chipped-concrete",
    ),
    slab(
      "near-right-edge-chip",
      "near-right chipped aperture edge",
      "broken-brick",
      0.14,
      [
        { x: -1.12, y: -0.46, z: 0.9 },
        { x: -0.45, y: -0.48, z: 0.84 },
        { x: -0.73, y: -0.72, z: 0.28 },
      ],
      "near-lip",
      "edge-fragment",
      "brick-spall",
    ),
    slab(
      "far-left-edge-chip",
      "far-left chipped aperture edge",
      "broken-brick",
      0.15,
      [
        { x: 1.18, y: -0.45, z: -0.92 },
        { x: 0.45, y: -0.47, z: -0.84 },
        { x: 0.73, y: -0.7, z: -0.28 },
      ],
      "far-lip",
      "edge-fragment",
      "brick-spall",
    ),
    slab(
      "far-right-edge-chip",
      "far-right chipped aperture edge",
      "damp-concrete",
      0.17,
      [
        { x: 1.15, y: -0.46, z: 0.92 },
        { x: 0.72, y: -0.7, z: 0.35 },
        { x: 0.42, y: -0.47, z: 0.88 },
      ],
      "far-lip",
      "edge-fragment",
      "chipped-concrete",
    ),
    slab(
      "left-near-rim-chip",
      "left-near irregular rim chip",
      "broken-brick",
      0.13,
      [
        { x: -0.8, y: -0.43, z: -1.22 },
        { x: -0.25, y: -0.69, z: -0.62 },
        { x: 0.1, y: -0.44, z: -1.18 },
      ],
      "left-bank",
      "edge-fragment",
      "brick-spall",
    ),
    slab(
      "left-far-rim-chip",
      "left-far irregular rim chip",
      "damp-concrete",
      0.12,
      [
        { x: 0.25, y: -0.45, z: -1.2 },
        { x: 0.55, y: -0.68, z: -0.55 },
        { x: 0.95, y: -0.43, z: -1.14 },
      ],
      "left-bank",
      "edge-fragment",
      "chipped-concrete",
    ),
    slab(
      "right-near-rim-chip",
      "right-near irregular rim chip",
      "damp-concrete",
      0.14,
      [
        { x: -0.78, y: -0.44, z: 1.2 },
        { x: 0.08, y: -0.45, z: 1.15 },
        { x: -0.27, y: -0.7, z: 0.58 },
      ],
      "right-bank",
      "edge-fragment",
      "chipped-concrete",
    ),
    slab(
      "right-far-rim-chip",
      "right-far irregular rim chip",
      "broken-brick",
      0.13,
      [
        { x: 0.22, y: -0.44, z: 1.18 },
        { x: 0.92, y: -0.43, z: 1.12 },
        { x: 0.57, y: -0.68, z: 0.55 },
      ],
      "right-bank",
      "edge-fragment",
      "brick-spall",
    ),
    slab(
      "near-left-fracture",
      "near-left aperture-radial fracture",
      "fracture-shadow",
      0.04,
      [
        { x: -0.92, y: -0.75, z: -0.66 },
        { x: -1.78, y: -0.74, z: -0.94 },
        { x: -1.05, y: -0.76, z: -0.54 },
      ],
      "fracture-seam",
      "near-lip",
    ),
    slab(
      "near-right-fracture",
      "near-right aperture-radial fracture",
      "fracture-shadow",
      0.035,
      [
        { x: -0.9, y: -0.75, z: 0.63 },
        { x: -1.06, y: -0.76, z: 0.5 },
        { x: -1.76, y: -0.74, z: 0.96 },
      ],
      "fracture-seam",
      "near-lip",
    ),
    slab(
      "far-left-fracture",
      "far-left aperture-radial fracture",
      "fracture-shadow",
      0.04,
      [
        { x: 0.9, y: -0.74, z: -0.62 },
        { x: 1.78, y: -0.73, z: -0.91 },
        { x: 1.04, y: -0.75, z: -0.5 },
      ],
      "fracture-seam",
      "far-lip",
    ),
    slab(
      "far-right-fracture",
      "far-right aperture-radial fracture",
      "fracture-shadow",
      0.035,
      [
        { x: 0.88, y: -0.74, z: 0.61 },
        { x: 1.02, y: -0.75, z: 0.49 },
        { x: 1.75, y: -0.73, z: 0.94 },
      ],
      "fracture-seam",
      "far-lip",
    ),
    slab(
      "left-near-fracture",
      "left-near bank radial fracture",
      "fracture-shadow",
      0.038,
      [
        { x: -0.45, y: -0.74, z: -1.06 },
        { x: -0.96, y: -0.72, z: -2.06 },
        { x: -0.32, y: -0.75, z: -1.15 },
      ],
      "fracture-seam",
      "left-bank",
    ),
    slab(
      "left-far-fracture",
      "left-far bank radial fracture",
      "fracture-shadow",
      0.034,
      [
        { x: 0.42, y: -0.73, z: -1.05 },
        { x: 0.28, y: -0.74, z: -1.15 },
        { x: 0.9, y: -0.71, z: -2.08 },
      ],
      "fracture-seam",
      "left-bank",
    ),
    slab(
      "right-near-fracture",
      "right-near bank radial fracture",
      "fracture-shadow",
      0.036,
      [
        { x: -0.43, y: -0.74, z: 1.05 },
        { x: -0.3, y: -0.75, z: 1.15 },
        { x: -0.92, y: -0.72, z: 2.05 },
      ],
      "fracture-seam",
      "right-bank",
    ),
    slab(
      "right-far-fracture",
      "right-far bank radial fracture",
      "fracture-shadow",
      0.038,
      [
        { x: 0.4, y: -0.73, z: 1.04 },
        { x: 0.94, y: -0.71, z: 2.06 },
        { x: 0.27, y: -0.75, z: 1.14 },
      ],
      "fracture-seam",
      "right-bank",
    ),
  ],
} satisfies MeshObjectProfile;

export type CollapsedCeilingObjectKitConfig = MeshGeneratingObjectKitConfig;

export const collapsedCeilingObjectKitConfig =
  createMeshGeneratingObjectKitConfig(collapsedCeilingObjectProfile);

export const generateCollapsedCeilingMesh = () =>
  createMeshObjectDescriptor(collapsedCeilingObjectProfile);

export const createCollapsedCeilingObjectKit = (
  config: CollapsedCeilingObjectKitConfig = collapsedCeilingObjectKitConfig,
): HorrorDomainKit =>
  createMeshGeneratingObjectKit(collapsedCeilingObjectProfile, config);
